---
apiVersion: v1
kind: Namespace
metadata:
  name: bpf-daemonset
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpf-daemonset
  namespace: bpf-daemonset
spec:
  selector:
    matchLabels:
      name: bpf-daemonset
  template:
    metadata:
      labels:
        name: bpf-daemonset
    spec:
      containers:
      - name: bpf-daemonset
        image: danielpacak/bpf-go-daemonset-template:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: sys-kernel-debug
          mountPath: /sys/kernel/debug
          readOnly: true
      volumes:
      - name: sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug
