---
name: PR Created
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  quick-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
      - name: Run Unit Tests
        run: |
          make unit-tests
  integration-tests:
    runs-on: ubuntu-22.04
    needs:
      - quick-check
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
      - name: Run Integration Tests
        run: |
          make integration-tests
  e2e-tests:
    runs-on: ubuntu-22.04
    needs:
      - integration-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - name: Start Minikube
        uses: medyagh/setup-minikube@d8c0eb871f6f455542491d86a574477bd3894533 # v0.0.18
        with:
          driver: docker
      - name: Build image
        run: |
          make image
          minikube image load danielpacak/bpf-go-daemonset-template:latest
      - name: Deploy to minikube
        run: |
          kubectl apply -f deploy/kubernetes/all.yml
          kubectl rollout status --timeout 3m ds -n bpf-daemonset bpf-daemonset
      - name: Run tests
        run: |
          make e2e-tests
          kubectl logs -n bpf-daemonset daemonset/bpf-daemonset
